### ISSUE TITLE
"precondition failed"

### ISSUE THREAD

**Issue by kurtkincaid** [partoutx/connect-arangodb-session#3]
I am getting the following error, but only intermittently:

{ ArangoError: precondition failed
    at new ArangoError (c:\my\path\cse\cryptoservicesengine\node_modules\connect-arangodb-session\node_modules\arangojs\lib\error.js:30:15)
    at c:\my\path\cse\cryptoservicesengine\node_modules\connect-arangodb-session\node_modules\arangojs\lib\connection.js:204:21
    at callback (c:\my\path\cse\cryptoservicesengine\node_modules\connect-arangodb-session\node_modules\arangojs\lib\util\request.node.js:52:9)
    at IncomingMessage.<anonymous> (c:\my\path\cse\cryptoservicesengine\node_modules\connect-arangodb-session\node_modules\arangojs\lib\util\request.node.js:63:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at Connection.promisify (c:\my\path\cse\cryptoservicesengine\node_modules\connect-arangodb-session\node_modules\arangojs\lib\util\promisify.js:26:19)
    at DocumentCollection.update (c:\my\path\cse\cryptoservicesengine\node_modules\connect-arangodb-session\node_modules\arangojs\lib\collection.js:259:53)
    at c:\my\path\cse\cryptoservicesengine\node_modules\connect-arangodb-session\index.js:260:27
  errorNum: 1200,
  code: 412,
  response:
**[snip]**
     body:
      { error: true,
        code: 412,
        errorNum: 1200,
        errorMessage: 'precondition failed',
        _id: 'sessionStore/b60944cb-42d3-4ebf-bc5a-e908859134d1',
        _key: 'b60944cb-42d3-4ebf-bc5a-e908859134d1',
        _rev: '_XexbcHW--_' } } }

Because it is intermittent, I am having a heck of a time figuring out what exactly the problem is. Per the ArangoDB documentation, an error of 1200 indicates a revision conflict, but I am at a loss as to how to correct it.

Thanks in advance.

Kurt

**Comment by gbevan** [comment]
Hi Kurt.  I'm not really maintaining this project anymore, havent done for a while now.
Looking at the stack trace, it is more likely either an issue with arangojs (maybe the version being pulled in is now is out of date - see package.json - also see the forks of this project, i think someone mentions there about updating dependencies), or you're somehow trying to insert a document with a duplicate revision.

**Comment by kurtkincaid** [comment]
Got it. Ok. Thanks for the info.
