### ISSUE TITLE
UnauthorizedError: Unauthorized

### ISSUE THREAD

**Issue by brumsel** [partoutx/connect-arangodb-session#4]
Although I used the correct parameters I receive an Unauthorized error while connecting to  ArangoDB. See below for the error message.

After some tweaking I was able to resolve this issue by changing some lines in the index.js file.
I will create a new pull request for my solution. I hope you can merge that pull request so I don't have to adjust it if I npm install this again in another project. I probably forgot what I did to solve it. ;-)

```javascript
Failed to talk to ArangoDB, maybe the service isn't running?: { UnauthorizedError: Unauthorized
    at /home/frank/WebstormProjects/arangojs/node_modules/connect-arangodb-session/node_modules/arangojs/lib/connection.js:209:46
    at callback (/home/frank/WebstormProjects/arangojs/node_modules/connect-arangodb-session/node_modules/arangojs/lib/util/request.node.js:52:9)
    at IncomingMessage.<anonymous> (/home/frank/WebstormProjects/arangojs/node_modules/connect-arangodb-session/node_modules/arangojs/lib/util/request.node.js:63:11)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
From previous event:
    at new ArangoDBStore (/home/frank/WebstormProjects/arangojs/node_modules/connect-arangodb-session/index.js:73:8)
    at Object.<anonymous> (/home/frank/WebstormProjects/arangojs/app.js:28:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
  message: 'Unauthorized',
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        paused: false,
        emitClose: true,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: false,
     _events: [Object: null prototype] { end: [Array], data: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'localhost',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'localhost',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { 'x-content-type-options': 'nosniff',
        'www-authenticate': 'Bearer token_type="JWT", realm="ArangoDB"',
        server: 'ArangoDB',
        connection: 'Keep-Alive',
        'content-type': 'text/plain; charset=utf-8',
        'content-length': '0' },
     rawHeaders:
      [ 'X-Content-Type-Options',
        'nosniff',
        'Www-Authenticate',
        'Bearer token_type="JWT", realm="ArangoDB"',
        'Server',
        'ArangoDB',
        'Connection',
        'Keep-Alive',
        'Content-Type',
        'text/plain; charset=utf-8',
        'Content-Length',
        '0' ],
     trailers: {},
     rawTrailers: [],
     aborted: false,
     upgrade: false,
     url: '',
     method: null,
     statusCode: 401,
     statusMessage: 'Unauthorized',
     client:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'localhost',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: null,
        [Symbol(asyncId)]: -1,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     _consuming: false,
     _dumped: false,
     req:
      ClientRequest {
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'GET /_db/_system/_api/database/user HTTP/1.1\r\ncontent-type: text/plain\r\ncontent-length: 0\r\nx-arango-version: 30000\r\nHost: localhost:8529\r\nConnection: keep-alive\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/_db/_system/_api/database/user',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     body: '' } }
```

**Comment by gbevan** [comment]
Hi @brumsel  i've merged your pull request.  FYI - I dont really support this project anymore, but i'm happy to merge fixes like this.
